
import React, { useState } from 'react';
import { DEFAULT_USER_DATA } from './constants';
import { UserData } from './types';
import FinancialReport from './components/FinancialReport';
import { LayoutDashboard, FileText, Settings, User, LogOut, Menu, X, Sparkles, PieChart } from 'lucide-react';

const App: React.FC = () => {
  const [userData, setUserData] = useState<UserData>(DEFAULT_USER_DATA);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  return (
    <div className="min-h-screen flex bg-[#fdfdfd]">
      {/* Mobile Sidebar Toggle */}
      <button 
        className="lg:hidden fixed top-4 right-4 z-50 p-2 bg-white rounded-xl shadow-lg border border-slate-200"
        onClick={() => setIsSidebarOpen(!isSidebarOpen)}
      >
        {isSidebarOpen ? <X size={24} /> : <Menu size={24} />}
      </button>

      {/* Sidebar */}
      <aside className={`
        fixed inset-y-0 left-0 z-40 w-72 bg-white border-r border-slate-100 transform transition-transform duration-300 ease-in-out
        lg:translate-x-0 lg:static lg:inset-0
        ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}
      `}>
        <div className="h-full flex flex-col">
          <div className="p-8">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-indigo-600 rounded-2xl flex items-center justify-center text-white shadow-xl shadow-indigo-100">
                <Sparkles size={24} />
              </div>
              <div className="flex flex-col">
                <span className="text-lg font-extrabold text-slate-900 leading-none">AI-Financial</span>
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mt-1">Advisor</span>
              </div>
            </div>
          </div>

          <nav className="flex-1 px-4 space-y-2">
            <SidebarItem icon={<LayoutDashboard size={20} />} label="Dashboard" active />
            <SidebarItem icon={<PieChart size={20} />} label="Cash Flow" />
            <SidebarItem icon={<FileText size={20} />} label="Wealth Reports" />
            <SidebarItem icon={<User size={20} />} label="My Profile" />
            <SidebarItem icon={<Settings size={20} />} label="Preferences" />
          </nav>

          <div className="p-6 mt-auto">
            <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100 flex items-center gap-3 group cursor-pointer hover:bg-white hover:shadow-md transition-all">
              <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold text-sm">
                {userData.Name.charAt(0)}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-bold text-slate-800 truncate">{userData.Name}</p>
                <p className="text-[10px] text-slate-400 font-bold truncate uppercase tracking-tighter">{userData.email}</p>
              </div>
              <LogOut size={16} className="text-slate-300 group-hover:text-rose-400 transition-colors" />
            </div>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-y-auto">
        <FinancialReport data={userData} />
        
        {/* Footer */}
        <footer className="max-w-7xl mx-auto px-8 py-16 border-t border-slate-100 text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Sparkles size={16} className="text-indigo-400" />
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">AI-Financial Advisor</span>
          </div>
          <p className="text-slate-400 text-[10px] max-w-2xl mx-auto leading-relaxed font-medium">
            Disclaimer: This report is generated by an advanced AI model for informational purposes only. 
            It does not constitute formal financial advice. Please consult with a SEBI-registered investment advisor 
            before making significant financial decisions. Market investments are subject to risks.
          </p>
        </footer>
      </main>

      {/* Overlay for mobile sidebar */}
      {isSidebarOpen && (
        <div 
          className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-30 lg:hidden"
          onClick={() => setIsSidebarOpen(false)}
        ></div>
      )}
    </div>
  );
};

const SidebarItem: React.FC<{ icon: React.ReactNode; label: string; active?: boolean }> = ({ icon, label, active }) => (
  <div className={`
    flex items-center gap-3 px-5 py-3.5 rounded-2xl cursor-pointer transition-all duration-200
    ${active 
      ? 'bg-indigo-600 text-white shadow-xl shadow-indigo-100 font-bold' 
      : 'text-slate-500 hover:bg-slate-50 hover:text-slate-900 font-semibold'}
  `}>
    {icon}
    <span className="text-sm">{label}</span>
  </div>
);

export default App;
